### ISSUE TITLE
Document authentication in Javascript

### ISSUE THREAD

**Issue by leplatrem** [spiral-project/daybed#103]
Example, snippet, ... it should be very easy to use Daybed with Javascript.
If not, then get rid of authentication by default.

**Comment by Natim** [comment]
In JS there is no problem because we have persona.

**Comment by Natim** [comment]
It is as simple as http://localhost:8000/persona :)

**Comment by leplatrem** [comment]
It looks rather simple, indeed (https://developer.mozilla.org/en/Persona/Quick_Setup)

I'll confirm it's as simple as you say when upgrading backbone-daybed to `dev` branch :)

**Comment by leplatrem** [comment]
We shall have a look at http://oauth.io too :)

**Comment by leplatrem** [comment]
Since login and logout views check for a number of things, I cannot see how to perform **remote** authentication in Javascript. 
- audience parameter restricts remote authenticated to a limited set of websites.
- crsf is checked (remotely we don't have the session token)
- cors is not enabled (ref #137)

In pyramid_persona, this is achieved through JS server side templating :( 
https://github.com/madjar/pyramid_persona/blob/master/pyramid_persona/utils.py#L29
https://github.com/madjar/pyramid_persona/blob/master/pyramid_persona/templates/persona.js#L17

How could we allow any JS website or mobile app to authenticated on our storage-as-a-service API ? Can we serve the session token as JSON ? Should we disable audience checks like CORS with `'*'` ?

As a reference, here is the remote HTML page (running on localhost:9999) that I use to login on daybed (running on localhost:8000) 
https://friendpaste.com/6Zj4fEIqshHqDs5Ptpd892
Like explained in https://developer.mozilla.org/en/Persona/Quick_Setup

**Comment by almet** [comment]
The audience can be set to "*" if that's how we intend to use it. I guess in JS apps, people would have to set their audience to the server we are running, nope?

**Comment by leplatrem** [comment]
In JS app, we don't specify the audience, so that would work indeed !

What do you think of : 
- adding CORS to `/login` ?
- providing crsf token in `/login` response headers ?

This way, remote authentication in JS would be : 
- obtain the Persona `assertion` using the [official Persona JS lib](https://developer.mozilla.org/en/Persona/Quick_Setup) (the one that prompts in a popup)
- perform a `HEAD` on `/login` to obtain the crsf token
- perform a `POST` on `/login` using both  `assertion` and `crsf` (requires CORS)

@ametaireau, could you start by adding CORS on login/logout views please ?
In the mean time, I will do my best to contribute to _pyramid persona_ :)

**Comment by leplatrem** [comment]
For reference :
https://github.com/madjar/pyramid_persona/issues/15
https://github.com/madjar/pyramid_persona/issues/16

**Comment by almet** [comment]
I'm closing this one for now since it seems we don't want to use persona anymore.
