### ISSUE TITLE
Rename data_item to record

### ISSUE THREAD

**Issue by leplatrem** [spiral-project/daybed#105]
Reading this : 
http://en.wikipedia.org/wiki/Data_item
and this :
http://en.wikipedia.org/wiki/Record_(computer_science)

`record` looks a lot more relevant :)

**Comment by almet** [comment]
Good catch. +1

**Comment by arnaudbos** [comment]
+1 also.

**Comment by leplatrem** [comment]
And what about that `data` ?
https://github.com/spiral-project/daybed/blob/dev/daybed/backends/couchdb/views.py#L27
https://github.com/spiral-project/daybed/blob/dev/daybed/backends/couchdb/database.py#L67
