### ISSUE TITLE
Speedup tests

### ISSUE THREAD

**Issue by almet** [spiral-project/daybed#107]
Tests are taking a lot of time to run at the moment, and that makes it hard to test changes in an efficient way.

Investigate why this is slow and make it fast :-)

**Comment by almet** [comment]
After doing some analysis, it seems that 55% of the time is spent in the method `recv` of the `socket` module.
This is mainly due to the fact that we're using CouchDB in the tests.

I found [nose-talisker](https://github.com/andymckay/nose-talisker) and [runsnakerun](http://www.vrplumber.com/programming/runsnakerun/) particularly helpful here :)

**Comment by leplatrem** [comment]
This is adressed by the PR #83

**Comment by almet** [comment]
`Ran 210 tests in 26.435s`.

Great, thanks @leplatrem & @AntoineCezar :+1:
