### ISSUE TITLE
Get rid of put_data, post_data and delete_data permissions ?

### ISSUE THREAD

**Issue by leplatrem** [spiral-project/daybed#111]
Is there a use-case where we need a distinction between `delete_record` and `delete_data` ? Or between `post_data` and `post_record` ?

Intuitively we can merge those permissions, since they both concern records. If you envisionned the opposite, please argue in the docs/ :)

**Comment by Natim** [comment]
It is completly different. Data is about collection, record is about an specific item.

Data is to get all the record in one.

**Comment by Natim** [comment]
Sorry I forget to read the word "permissions".

The difference stand between the creator of the record.
You can say that only the author of a record can delete as well as the admin of the model.

data is linked to model permissions.
record is linked to record permissions.

**Comment by leplatrem** [comment]
Ok, got it, it makes sense.

But is there a use-case where we would give `post_data` and not `post_record` ?

There may be a lack of use-cases/examples in documentation then. Shall we reopen #65 ?

**Comment by Natim** [comment]
I think the #65 is not enough precise, we should open more precise ticket so we can say objectively it is fixed or not.

I don't think there is a `post_record` actually because post is only on collections.
