### ISSUE TITLE
Rename data to collection

### ISSUE THREAD

**Issue by almet** [spiral-project/daybed#112]
`data` is a generic term. Since a `data` contains `record`, we could change it to `collection` instead.

What do you think?

**Comment by arnaudbos** [comment]
+1! Semantic matters.

**Comment by Natim** [comment]
Actualy `data` is related to models.

```
/models/todo/data
```

`collection` is a synonim of `list` but data is an attribute of the models.

```
/models/todo/collection
```

Does that URL make sense for you?

The model has a `definition`, `data`, `roles` and a `policy`.

:-1: on this one.

**Comment by leplatrem** [comment]
`records` :question:

**Comment by Natim** [comment]
yes much better :+1:

**Comment by almet** [comment]
WFM as well.

**Comment by leplatrem** [comment]
It would also avoid confusion with `data` in database entries, which refers to _attributes_ :)
https://github.com/spiral-project/daybed/blob/dev/daybed/backends/couchdb/database.py#L70

**Comment by Natim** [comment]
I guess we now just need to rename `data.py` in `records.py`

**Comment by leplatrem** [comment]
And replace `/data` with `/records` in urls.

And I also suggest we keep `data` for _records_ attributes only. And use `records` instead of `data` for storing and posting model records.

**Comment by Natim** [comment]
Yes.
