### ISSUE TITLE
Prevent user to have username ``system.EveryOne`` ?

### ISSUE THREAD

**Issue by leplatrem** [spiral-project/daybed#117]
https://github.com/spiral-project/daybed/blob/dev/daybed/backends/couchdb/database.py#L180

**Comment by Natim** [comment]
Actually both constants USER_AUTHENTICATED and USER_EVERYONE
https://github.com/spiral-project/daybed/blob/dev/daybed/acl.py#L13L14

**Comment by Natim** [comment]
But actually it is not a security issue it will just doesn't change anything if somebody adds this users.
We could but we don't need to prevent it I think.
