### ISSUE TITLE
Split code from daybed/__init__.py ?

### ISSUE THREAD

**Issue by leplatrem** [spiral-project/daybed#119]
Looks like configuration of application became quite heavy...
https://github.com/spiral-project/daybed/blob/dev/daybed/__init__.py#L53-L148

**Comment by Natim** [comment]
Yes we should split what is related to daybed and what is related to daybed instance.
Everything related to daybed instance should stand in development.ini with default values.
Everything else can stay in **init**.py

We could also create some functions in a config.py module if necessary.

**Comment by almet** [comment]
most of the stuff here is related to Persona integration.

I propose we re-assess this once persona integration had been removed.

What you're talking about @natim is something different, I think, but still I agree: we should let the config.ini file be as simple as possible.

**Comment by Natim** [comment]
Persona as been removed by #178

**Comment by Natim** [comment]
I think it is much more acceptable now. @leplatrem can we close?
