### ISSUE TITLE
Records formatting

### ISSUE THREAD

**Issue by leplatrem** [spiral-project/daybed#12]
`Accept` HTTP directive may not be enough to format records.

For example, getting the records of a model which contain a geometry as JSON may have two formattings :
- a basic JSON (as currently : `[ {...}, {...} ]`)
- a GeoJSON ( `{ "type": "FeatureCollection", "features": [{...}, {...}]`), that integrates nicely in JS map widgets like Leaflet.

Both are valid JSON. We might need a `?format=XXX` parameter to specify which layout it should have.

**Comment by almet** [comment]
OH, we could actually use vendor specific data in the Accept / Content-Type fields. For instance "application/geojson+json" / "application/json" ?

**Comment by leplatrem** [comment]
AFAIK there is no consensus for geojson mimetype.

I used `application/geojson` : we could use `application/geo+json`, but @sgillies does not seem to like it :)

How do we trigger the geojson serializer otherwise ?

**Comment by sgillies** [comment]
You're right, I don't like application/geojson or application/geo+json :) And we can't just make up new application media types, they need to be registered.

I recommend following http://tools.ietf.org/html/rfc6906 and adding a profile media type parameter like

```
application/json; profile=http://example.com/profiles/geojson
```

We'll have a standard GeoJSON profile URI at some point, but I'm not sure what it would be. In the meanwhile, you can make one specifically for your spiral-project GeoJSON files.

**Comment by almet** [comment]
Profiles might effectively be an idea. It also means we need to extend SPORE to support this concept and check cornice / pyramid allow this easily.

**Comment by leplatrem** [comment]
Thanks Sean for taking time to give hints on that !
It's completely new for me, but looks just the right thing :)
