### ISSUE TITLE
Why do we need a /personna page ?

### ISSUE THREAD

**Issue by leplatrem** [spiral-project/daybed#122]
Since Daybed is an API, why do we need `/personna` with Mako etc. ?

**Comment by Natim** [comment]
Well, the basic answer is to enable persona authentication in daybed.

Persona needs a server to validate authentication and daybed needs to bind the persona user with the daybed user.

Mako is not really related to persona but it is a lightweight template system that was first default in pyramid, it is why we choosed it in the first place.

One of the aim I have for daybed is to have it as a Javascript APP only backend for localstorage synchronization.
In that case the /persona url is really useful.

I hope this is enough to answer your question.

**Comment by leplatrem** [comment]
I still don't get why do we need HTML :(

As for Javascript apps, why JSON end-points are not enough ?

**Comment by leplatrem** [comment]
Relates to #103

**Comment by leplatrem** [comment]
We should definitely get rid of this page. It's useless for JS authentication !

**Comment by almet** [comment]
+1, we should remove it.

**Comment by almet** [comment]
Closing this for now, I'll create a new and updated bug about the next steps for auth.
