### ISSUE TITLE
Add a POST method for definitions

### ISSUE THREAD

**Issue by almet** [spiral-project/daybed#14]
I found myself trying to find a name for my definition even if I didn't needed one. That could be useful to have daybed deciding directly this kind of things for us. I like heroku which is choosing some names that "could" be real worlds, rather than using hashed of some sort.

**Comment by leplatrem** [comment]
generated name will be given back to user using a redirect ? (not a REST expert)
or should we add a field in model definition json ?

**Comment by almet** [comment]
we should create the model name and return it automatically. I think that returning 200 + the address of the newly created resource would be enough.

**Comment by leplatrem** [comment]
thought of you when read this : http://sametmax.com/generateur-de-nom-dheroic-fantasy-en-python/

**Comment by AntoineCezar** [comment]
I take this one. With a pluggable name generator.
