### ISSUE TITLE
Rethink authentication

### ISSUE THREAD

**Issue by almet** [spiral-project/daybed#150]
Currently, daybed uses persona for authentication.

It seems that's not exactly what we want, since persona can only be used in a web context for now. Also, the project is not anymore actively maintained by mozilla, so this is not likely to change in the near future.

My proposal:
- Create an endpoint for users to create accounts;
- Let them authenticate with different authentication schemes: Digest and Hawk authentication.

In the future, we could consider generating multiple hawk tokens for the users, so they can delegate access to their accounts to 3rd parties. Also, Hawk has a concept of "bewits" for this specific use case, that we may consider.

But I would prefer to keep this as a post 1.0 feature, so we can focus on what's important for now: having authentication that just works.

**Comment by almet** [comment]
I'm wondering if that could make sense to actually integrate with Velruse, which proposes a way to integrate with 3rd parties. See http://velruse.readthedocs.org/en/latest/index.html

Thoughts?

**Comment by almet** [comment]
We've been talking with @natim about authentication, and it seems that we need to solve different problems.

## How one logs into daybed?

(That's what we were solving before with the persona integration.)

We want to be able to log from different identity providers (github, facebook, google, twitter, SAML etc.). We don't want daybed to deal with password and email validation, for instance.

## How do we delegate daybed data access to 3rd party HTML apps?

In other words: how can an application get hawk credentials?

Here is a tentative flow:
- An user is directed to the daybed website and prompted to authorize access to a 3rd party app (a list of models to access is prompted);
- The user clicks on "YES"
- Hawk creds are sent back to the app (see implementation hereafter).

### Web Socket implementation
- The client creates a Web Socket connection with the server;
- It requests an UUID from the server and stores it;
- When the user is directed to the authorize page, the page is given this UUID;
- When the user clicks on YES, the server is notified, the server generates hawk credentials, finds back the right websocket connection with the UUID and sends it back the hawk credentials via the web socket.

### Simple Push

Quite similar, but not exactly (see https://gist.github.com/matzew/cbda360d72eaaef75971):
- You create the websocket
- You request an URL
- You give this URL to Daybed
- Daybed stores the hawk credentials somewhere and call the URL with a version number
- It wakes up the client using the websocket
- Client asks credentials using its Simple Push URL + Version number.

### Another (maybe simpler) way: SSE

Not sure how exactly yet, see https://developer.mozilla.org/en-US/docs/Server-sent_events/Using_server-sent_events

## How do we delegate daybed data access to 3rd party server apps?

That's already the case now. When you're authenticated, you can generate new hawk credentials directly (using a web interface).

**Comment by almet** [comment]
We've had some more discussions about that today.

It seems that the way to go for daybed would be to just ditch out any authentication form and let users access data with a generated token, that they're given when they create the definition.

In other words, it could be something like that:
1. The client sends a request to create the definition. This client says it wants to create a number of ACLs.
2. The definition is created, tokens are generated and returned to the client.
3. When the client sends requests to create a model / send data, it signs it requests using this token.

A first version could just send the token in a header, future versions could sign the requests using hawk for instance.

**Comment by Natim** [comment]
This is what we had for the first version of Daybed (the one released) and we got rid of it because if you forget the token you loose your data.

What we wanted is a way to generate a new token for the same user on a new device.

**Comment by almet** [comment]
That is not exactly what we had. There weren't any concept of ACLs for instance.

Token storage will be provided by a different service, named daybed-admin.

**Comment by Natim** [comment]
I don't get it can you make a flow chart?

**Comment by almet** [comment]
It's about scope.

This lets daybed be a simple service, with no information about accounts.

![daybed](https://cloud.githubusercontent.com/assets/67073/3102089/46aa7050-e641-11e3-8e8a-5f2e3867ab0f.png)

**Comment by Natim** [comment]
So you are creating tokens for definition and one for each record?
How do you manager CRUD permissions?

Case where only the definition creator can read the records
Case where everybody can read everything
Case where the author of records can update/delete them?
Case where I can read only the records I made and the definition creator cannot?

**Comment by almet** [comment]
Here is a way to do it:

**Case where only the definition creator can read the records**
you actually have different tokens. In my mind, when you request the creation of a definition, you ask for different permission tokens.

For instance, you can ask for "admin" and "create new records", and these two would be generated.

**Case where everybody can read everything**
You just say that in the definition, and then there is no need to authenticate to read.

**Case where the author of records can update/delete them?**
On this one, I think the client can generate another token that we attach to the records, if you want to modify what you did, then you need to give again this same token.

**Case where I can read only the records I made and the definition creator cannot?**
I don't think that's a case we want to handle, at least for now.

**Comment by Natim** [comment]
The last case is the default case for remoteStorage usage of Daybed.

I see two things: Be able to choose the token you want to use for records and definition (so you can use the same for multiple permissions and multiple records/definitions.)

Then you can ask all the records for a specific definition and token.

**Comment by Natim** [comment]
Or we can also say that an application generate a token and name all the definition it needs with this token as a prefix. Then we always return all the records for this token and if we want to share data we use the same token (the app can make a link to share the token between devices or using daybed-share)

**Comment by almet** [comment]
-1 on the prefix proposal. I don't understand what that buys us.
+1 on the fact to specify which tokens you want to see used.

To add more on the last case: "I can read only the records I made and the definition creator cannot", we can also support that if needed at creation time. You give the permission mask you want to use and we (eventually generate a token and) associate it to the definition.

**Comment by Natim** [comment]
Fixed by #176
