### ISSUE TITLE
Get collection of my records

### ISSUE THREAD

**Issue by leplatrem** [spiral-project/daybed#179]
Wouldn't it relevant to filter the returned results of the `get_records` view ?
If I have the _read_all_records_ permission, I get them all. If I only have _read_my_records_, I get mine only.

Simple use case : a todolist application, one model for all users, all records are private. When opening the app on a new device, users synchronize their empty local storages with the collection returned by `/models/todoapp/records/`

**Comment by leplatrem** [comment]
related #90

**Comment by Natim** [comment]
Yes it would make sense also, I don't know if we can route view on permissions.

**Comment by almet** [comment]
Good idea. We can probably add some principals to the user to let the view know what it should do.

**Comment by Natim** [comment]
I have implemented a patch for this here:
- get_model: https://github.com/spiral-project/daybed/pull/185/files#diff-2fa9911728ff920d70c8b19150c3fc81R160
- get_records: https://github.com/spiral-project/daybed/pull/185/files#diff-d37c76536c0cc671b37242441ef06620R38

**Comment by leplatrem** [comment]
I lack of time to review all of this I am very sorry :|
(I receive a lot of notifications, which all look like good news to me :D, go on guyz!)

**Comment by leplatrem** [comment]
Usually I prefer dedicated pull-requests, easier to review and catch on :)

**Comment by Natim** [comment]
Yes I know but I did it as part as other changes.
