### ISSUE TITLE
Add a to string format string for the model

### ISSUE THREAD

**Issue by Natim** [spiral-project/daybed#190]
On an item list, it could be nice to have a way to define how we want to handle the format.

My proposal is to add a format field like so:

```
{
  "definition": {
    "title": "Mobile Originated Numbers",
    "description": "Associate a country code to a number",
    "format": "%(mcc)s - %(moVerifier)s",
    "fields": [
      {
        "name": "mcc",
        "label": "Mobile Country Code",
        "type": "regex",
        "regex": "^[0-9]{3}$"
      },
      {
        "name": "moVerifier",
        "label": "MO Verifier Number",
        "type": "string"
      }
    ]
  }
}
```

**Comment by leplatrem** [comment]
I don't get it :(

What do you mean by "handle the format" ?

**Comment by Natim** [comment]
When you want to display a list of records I would like to be able to define the verbose name of a record

**Comment by leplatrem** [comment]
Ok, get it. Do you think it should belong to the official API ?

Since you can store whatever you like in the model definition, it does not have to be officially supported... And it won't be used on the server side if I'm not mistaken

**Comment by Natim** [comment]
Yes you are right but we should document it for people that will use
daybed-admin.
Le 9 août 2014 09:54, "Mathieu Leplatre" notifications@github.com a écrit
:

**Comment by leplatrem** [comment]
Well, I guess this could be managed on daybed admin directly (pick columns to be shown ?).

In the backbone-daybed CRUD demo, I used to show records in a table with columns  http://spiral-project.github.io/backbone-daybed/#demo-poll-conf
