### ISSUE TITLE
Add definition PUT, that would create/update models

### ISSUE THREAD

**Issue by leplatrem** [spiral-project/daybed#231]
Would allow JS libs to fetch/save on the same URL

**Comment by Natim** [comment]
This? https://github.com/spiral-project/daybed/blob/master/daybed/views/models.py#L182-L198

**Comment by leplatrem** [comment]
Nope, on `/model/<modelid>/definition`, with the definition only in body

**Comment by Natim** [comment]
I am not sure we want this because we are already giving the definition only on the `/model/<model_id>` endpoint: http://daybed.readthedocs.org/en/latest/usage.html#model-management

**Comment by leplatrem** [comment]
But the permissions set required is different, that's one of the reasons we should allow definition PUT.
(e.g. I can have `read_definition` and `update_definition`, but not `delete_model` ... )
