### ISSUE TITLE
PUT/POST /models/:modelid/records with an unknown field type in the model definition (stored in the database) raise a 500

### ISSUE THREAD

**Issue by Natim** [spiral-project/daybed#246]
Assuming somone added the definition with an unknown type.

**Comment by magopian** [comment]
Can you please give steps to reproduce the issue?

**Comment by Natim** [comment]
So basically put an invalid model inside the database and try to add a record.

**Comment by leplatrem** [comment]
How do you put an invalid model ?

**Comment by Natim** [comment]
We add this bug when we were adding the annotation field and switching branch. I think we can close this as Invalid cause it shouldn't happen.
