### ISSUE TITLE
[Spore] Vérifier que le spore généré correspond bien à la spec SPORE

### ISSUE THREAD

**Issue by Natim** [spiral-project/daybed#26]
Il faut valider avec https://github.com/SPORE/specifications/blob/master/spore_validation.rx en utilisant https://github.com/rjbs/rx

**Comment by almet** [comment]
hmm, c'est bien cool ça :)

**Comment by Natim** [comment]
I did a first test here but it seams that validation doesn't work. https://github.com/spiral-project/daybed/tree/spore_schema_validation

It is not that easy to debug actually.

**Comment by Natim** [comment]
We can try it here : http://rx.codesimply.com/demo.html

**Comment by Natim** [comment]
I tried with a little working SPORE:

```
{
    "base_url": "http://localhost:8000",
    "expected_status": [200],
    "version": "0.1",
    "methods": {
        "put_data_item": {
            "path": "/data/:model_name/:data_item_id",
            "method": "PUT"
        }
    },
    "name": "daybed"
 }
```

**Comment by Natim** [comment]
Found the error : 

We defined `format: "json"` instead of `formats: ["json"]`

```
{
    "base_url": "http://localhost:8000",
    "expected_status": [200],
    "version": "0.1",
    "methods": {
        "put_data_item": {
            "path": "/data/:model_name/:data_item_id",
            "description": "Update a data item.",
            "required_params": ["model_name", "data_item_id"],
            "method": "PUT",
            "formats": ["json"]
        }
    },
    "name": "daybed"
}
```

**Comment by Natim** [comment]
just released : https://github.com/spiral-project/rxjson

**Comment by Natim** [comment]
Cornice does it for us.
