### ISSUE TITLE
Use httpie to demo daybed

### ISSUE THREAD

**Issue by almet** [spiral-project/daybed#28]
https://github.com/jkbr/httpie

that would probably be prettier than curl

**Comment by Natim** [comment]
Yes it would be good for the documentation examples :)

**Comment by almet** [comment]
I did that for the loop server documentation and that's indeed really useful and easy to read, see docs.services.mozilla.com/loop/apis.html

**Comment by Natim** [comment]
3 times yes, also we have made https://github.com/mozilla-services/requests-hawk which will empower us to add working API examples using hawk auth directly.

**Comment by almet** [comment]
FWIW, I've made some services documentation with it already and that's very useful :)

**Comment by Natim** [comment]
Great :+1: We are now using http as well as https://github.com/mozilla-services/requests-hawk for our documentation.
