### ISSUE TITLE
Add geometry field types

### ISSUE THREAD

**Issue by leplatrem** [spiral-project/daybed#30]
- Point
- Line
- Polygon
- Posted values will be coordinates list, like those stored in GeoJSON format
- Will be rendered as GeoJSON individually
- Collection of records will be rendered as GeoJSON only once issue #12 is implemented

**Comment by leplatrem** [comment]
Remains to be done :
- A point should not be a `colander.Sequence` but a `PointNode`
- Make use for `colander.Range` validators for GPS coordinates
- Add check on _LinearRing_ for polygons (last coordinate must be equal to first one).
- Add holes for polygons (list of _LinearRing_s : first is exterior, following are holes)

**Comment by leplatrem** [comment]
Done !

Would be glad if someone could review code and docstrings please !

**Comment by almet** [comment]
commented there. I think a pull request would have been more appropriate, however.

**Comment by almet** [comment]
Overall, I like it! We should probably put all that in a separate module (.geo ?) like you proposed.
Also add some functional tests for it.

**Comment by leplatrem** [comment]
Code review is not very convenient on Github indeed... But since I'm a "repo collab", a branch is appropriate isn't it ?

Regarding the separate module, shall I make `schemas` a package then ?

We can discuss here :
- the meaning and naming of that `gps` parameter instead of [there](https://github.com/spiral-project/daybed/commit/c2c56be4407ad6f83d45b0322112963d3e6ca5ff#commitcomment-2275318)
- the proper approach for unit testing deserializations. Actually I globally followed [the way colander does it](https://github.com/Pylons/colander/blob/master/colander/tests/test_colander.py#L733-L734)

**Comment by almet** [comment]
you can push a branch like you did and then issue a pullk request from this branch to master. that allows us to comment the overall diff.
