### ISSUE TITLE
Model relationships

### ISSUE THREAD

**Issue by leplatrem** [spiral-project/daybed#32]
We could envision a way to refer a model as a relationship :

Definition could look like:

```
{
"title": "Person",
"description": "An individual with a soul",
"fields": [
    {
        "name": "fullname",
        "type": "string",
    }, {
        "name": "brothers",
        "type": "many-to-many",
        "model": "Person"
    }
```

And an entry like : 

```
{
    "name":  "Howard",
    "brothers": [54321, 9876]
}
```

Validating this entry would mean checking that provided `brother` ids exist.

**Comment by almet** [comment]
make sense to me yep, +1. 

I'm wondering how we will export these then? Should we include the linked resources?

some comments about that, though:
1. should we include the complete uri of the resource instead of directly its id?
2. Do we want to have a many-to-many, one-to-many etc? or is a simple "foreign key" enough?

**Comment by leplatrem** [comment]
1. JSON schema seems to address this need with URI

```
     "storage": {
            "type": "object",
            "oneOf": [
                { "$ref": "#/definitions/diskDevice" },
                { "$ref": "#/definitions/diskUUID" },
            ]
        },
```
1. We would just need `anyOf` (1-N, N-N) and `oneOf` (1-1, N-1).
   But we first must clarify the distinction between linking data (records URIs) and linking model definitions (validating duplicated data against shared schemas).

In the end forseen applications are fun ! daybed could be a _data pad_, where some common models are shared (cities, vegetables, units, currencies...) and linked together (_ontologies_). Dataset loaded from dbpedia :)

**Comment by leplatrem** [comment]
Merged.
