### ISSUE TITLE
Allow pluggable storage backends

### ISSUE THREAD

**Issue by leplatrem** [spiral-project/daybed#42]
Idea by @AntoineCezar

**Comment by almet** [comment]
I'm a bit reluctant to the idea, mainly because it would mean having more HTTP calls to do the same thing.

We discussed that a bit at the cheese&code session, and wanted to implement that with a header (like X-VALIDATE-ONLY) or something like that.

An alternate solution is to propose another resource and to post / put there, but I'm wondering if that really makes sense, in term of REST / HTTP.

**Comment by leplatrem** [comment]
Actually, the idea was more in terms of architecture than API. 

Maybe we could forsee it as a "Pluggable storage system", so that daybed has several persistence backends. So far it is very tight to Couchdb.

**Comment by almet** [comment]
Agreed. That's the direction we've been taking anyway. that's fairly easy to add another backend at the moment, see https://github.com/spiral-project/daybed/blob/master/daybed/db.py#L11

We can add easily other "database connection" objects, and even reword a bit all that.

I've updated the title of this issue to reflect the actual discussion.

**Comment by leplatrem** [comment]
Yes, we're not that far !

If one wants a daybed without storage, we only have to implement a _dummy_ database connection, and specify its usage in settings ini file for example...

**Comment by almet** [comment]
Well, you need to have a storage anyway, because you need to create definitions anyway, I'm not sure having a "dummy" backend makes sence ;)

**Comment by AntoineCezar** [comment]
Shemas storage and data storage should be separatable in my opinion. So having a dummy data backend can do the trick.

**Comment by almet** [comment]
that can do the trick, right, but I still think that you may want to have this usecase sometimes, and store the data some other times, so I would not go this way, but explicitely add a way to do this instead (what do you think of the header proposal ?) (see #43 for it).

**Comment by leplatrem** [comment]
this last comment was not clear to me :(

Both aproaches, dummy backend and headers, make sense and are not exclusive. The first one concerns architecture/deployment, the second one is more about API usage (live validation on field update in a web form for example)

**Comment by almet** [comment]
frenchies talking english ;)

What I mean here is that it could work to have a dummy backend for this usecase, but I consider this a hack, and not a feature.

For instance, I would like, with the same deployment of daybed, be able to sometimes validate data and store it, and sometimes just validate data. Having to change the backend to allow the validation only usecase is a hack to me, doesn't it?

**Comment by AntoineCezar** [comment]
"One should be able to save the data to the backend of is choice" is the main point to me. What about using MongoDb, SQL databases or posting back to another service ?

"Will daybed provides a dummy backend implementation" should be discussed in another issue.

**Comment by almet** [comment]
@AntoineCezar we all agree on this point then. Feel free to open another issue if you feel like it for the dummy backend.

**Comment by AntoineCezar** [comment]
I have started some work on the subject: https://github.com/AntoineCezar/daybed/tree/issue_42_allow_pluggable_storage_backends
Things to look at:
- developpement.ini
- daybed/**ini**.py
- daybed/backends/testing.py
- daybed/views/*

If it's good, I'll go on:
- Making the tests pass with the testing backend
- Making couchdb work with the new structure

**Comment by almet** [comment]
thanks for working on this :-)

I commented there a few things, to recap briefly:
- Use classes for backends if possible
- don't expose too much to the views
- we should stay with the same db API, I think it's working out pretty well.
- don't include unrelated things in feature-oriented changesets (this can be hard to extract the interesting bits in case things are modified / rejected).

**Comment by AntoineCezar** [comment]
It seems that it's a good way to go. I'll do another draft before doing the real work unless you prefer directly pickable commits.

**Comment by almet** [comment]
works for me :)

**Comment by almet** [comment]
Any news on this?

**Comment by AntoineCezar** [comment]
Not yet. Some laziness + musical project. I'm in Paris this week so I don't know yet if i'll hack on it. But if your in a urge i'll give it a higher priority.

**Comment by AntoineCezar** [comment]
The new refactoring is started.
https://github.com/AntoineCezar/daybed/tree/issue_42

**Comment by leplatrem** [comment]
Implemented in #49
