### ISSUE TITLE
CORS doesn't work on 404ed resources

### ISSUE THREAD

**Issue by almet** [spiral-project/daybed#48]
when resources don't exist, we should return the right CORS headers. I'm not sure we're doing this ATM.

**Comment by leplatrem** [comment]
It looks like this applies to 400 too.

Wouldn't it be a Cornice bug instead ?

**Comment by leplatrem** [comment]
BTW, we have two ways of raising 404 :

https://github.com/spiral-project/daybed/blob/master/daybed/validators.py#L36
https://github.com/spiral-project/daybed/blob/master/daybed/views/data.py#L21, https://github.com/spiral-project/daybed/blob/master/daybed/views/definition.py#L23

**Comment by leplatrem** [comment]
Note: could this be a typo ? (`header`(s)) : https://github.com/mozilla-services/cornice/blob/master/cornice/schemas.py#L92

**Comment by almet** [comment]
ah right. I though I opened this to cornice. That's indeed a cornice bug.

**Comment by leplatrem** [comment]
Closed in Cornice :dancers: !
