### ISSUE TITLE
Token should be preserved after definition update

### ISSUE THREAD

**Issue by leplatrem** [spiral-project/daybed#59]
Does not seem to be the case:
https://github.com/spiral-project/daybed/blob/master/daybed/views/data.py#L45-L49

**Comment by almet** [comment]
Let's remove tokens for now?

**Comment by leplatrem** [comment]
Hum, I would say no :)

Just use the existing token on PUT...

**Comment by almet** [comment]
That's related to #61 which propose to remove the tokens for now until we find a better way to handle ACLs.
