### ISSUE TITLE
Remove tokens until proper ACL are implemented

### ISSUE THREAD

**Issue by AntoineCezar** [spiral-project/daybed#61]
The actual token system bring behaviors that does'nt look good to me.
When I POST data I excpect to get the full object with additionnal information like for exemple a "created_at".
In a POST based create definition I recive a token and have to follow a redirect to get the full object.
So unless there is a better way to pass tokens I suggest droping them for the moment.

**Comment by almet** [comment]
+1 for now.

**Comment by leplatrem** [comment]
:-1 

I would do exactly the contrary. Once we fix the ACLs, we can remove this custom approach.

Today, we can't allow "users" to update "author's" forms !

**Comment by almet** [comment]
If we consider what's deployed currently as a service ready-to-use, yes. I wasn't.

Anyway this means we need to implement proper ACLs soon. I don't really care which way we go (with or without them) in the first place, so whatever suits you best. We also can have two branches (dev and master) and I would only push master to stage.

Then we can remove ACLs from dev while working on a better ACL system.

**Comment by leplatrem** [comment]
I agree indeed. Leave that to the excitement of making daybed-map public :)

Would you agree to retain deployment lolnet until then ;) ? We still have source branching, don't we !

Ok for removing in master then.

**Comment by almet** [comment]
I'm not sure what you're referring to as "source branching"? I'm okay to let daybed.lolnet.org as-is for now.

We would need to agree on a branching / merging strategy. I never tried any of them. What do you think about the following:
- **master** is the stable branch, it is what we deploy.
- **dev** is where we develop. We merge new features to dev.
- When we're ready, we merge **dev** into **master** and make a release.

?

**Comment by leplatrem** [comment]
Yep, sounds like a very sane convention ! Agree !

**Comment by almet** [comment]
Done in the dev branch.
