### ISSUE TITLE
Implement authentication using Persona

### ISSUE THREAD

**Issue by Natim** [spiral-project/daybed#66]
Browser ID is a really good idea to use daybed as as javascript UI backend.

Basically we can then use the email as the account id for models and data management.

**Comment by leplatrem** [comment]
Would be great :) 

And might give a boost to our long ACL story #43

**Comment by Natim** [comment]
![board_snapshot_sep_06_2013__13_54_24_f6191f52-dfc0-44f5-a83c-809b9af30c06](https://f.cloud.github.com/assets/229453/1096267/d556ef42-16fb-11e3-84b0-b8b5ea9db5da.jpg)

**Comment by almet** [comment]
I HEREBY DECLARE MYSELF A DESIGNER.

**Comment by Natim** [comment]
Fixed :)
