### ISSUE TITLE
Change the default backend

### ISSUE THREAD

**Issue by almet** [spiral-project/daybed#84]
We're currently using CouchDB as a default backend, but the more I use it the more I regret it, specially because we're currently not using any feature it may have that's interesting to us.

What do you guys think about using a different backend, such as redis or mongodb instead? 

One of the reasons CouchDB seemed nice is that it's possible to plug ElasticSearch with it using the river API.

Do you have any experience setting-up something like that for the databases I'm mentioning?

Also, maybe that could make sense to record everything in a normal database (e.g. postgres).

Do you have any strong feelings on that?

**Comment by leplatrem** [comment]
I have nothing against it. There is are [redis](https://github.com/leeadkins/elasticsearch-redis-river) and [mongo](https://github.com/richardwilly98/elasticsearch-river-mongodb) rivers too!

I wish we could spend more energy in releasing and communicating instead, but that's my point of view...

**Comment by leplatrem** [comment]
Just discovered https://github.com/rethinkdb/rethinkdb :)

**Comment by Natim** [comment]
I have added redis as per #177
