### ISSUE TITLE
Check that users defined in model roles are valid

### ISSUE THREAD

**Issue by almet** [spiral-project/daybed#86]
This needs the branch ACL to be merged with dev, since it needs @leplatrem changes about passing the request to the schema validators.

When checking for roles at model creation time, we need to make sure the passed users actually exist, and if not, error out properly.

**Comment by leplatrem** [comment]
In the end, I didn't pass the request object to validators, but used this pattern : 

``` python
from pyramid.config import global_registries



class ModelExist(object):
    def __init__(self, db):
        self.db = db

    def __call__(self, node, value):
        model = self.db.get_model_definition(value)
        if not model:
            msg = u"Model '%s' not found." % value
            raise Invalid(node, msg)



...
db = global_registries.last.backend.db()
schema.add(SchemaNode(String(), name='model', validator=ModelExist(db)))


```

**Comment by Natim** [comment]
Should also be good by now.
