### ISSUE TITLE
Data item id format.

### ISSUE THREAD

**Issue by arnaudbos** [spiral-project/daybed#93]
I don't know if this has been discussed before but since I don't clearly see it in older issues, here it is.

On `dev` branch:

When I GET /models/todo/data, I receive ids with this format :

> "id": "todo-2c109e4892504d29b11f6ae8a96ccba7"

But when I GET /models/todo/data/todo-2c109e4892504d29b11f6ae8a96ccba7

> 404 Not Found.

However, GET /models/todo/data/2c109e4892504d29b11f6ae8a96ccba7 gives

> {
> status: "todo",
> item: "finish the documentation"
> }

I can see the "real ID recomposition" is made here: https://github.com/spiral-project/daybed/blob/dev/daybed/backends/couchdb/database.py#L24 but I don't really understand why this is done.

Wouldn't it be better to have explicit, auto-discoverable item ids when listing the collection resource? This way any client application could simply use the supplied ids instead of doing the same job of recomposing the item ids again and again.

Also, when I can, I prefer using absolute URLs when linking to other resources of my APIs. This makes easy to debug clickable links and makes all the API auto-discoverable, the clients just have to dive deeper by following a link and not recompose a URL.
Just a thought though.

Thanks!

P.S: What is the reason behind the "features" key and "Feature" type in the data items listing? Does the "feature" word represents a particular concept in daybed?

**Comment by leplatrem** [comment]
Indeed, you are completely right : ids should be explicit and match URIs.

What you describe here seems to be a regression introduced by @ametaireau in https://github.com/spiral-project/daybed/commit/f74eb0e5df7dea9df8cd5a690cab5f106aabff4d

> Does the "feature" word represents a particular concept in daybed?

This JSON layout is GeoJSON, and is used for plotting items on maps. Do you obtain this with default `Accept` headers ?
According to this test, you shouldn't https://github.com/spiral-project/daybed/blob/dev/daybed/tests/test_functional.py#L455-L463

**Comment by arnaudbos** [comment]
I'm just requesting the page from chrome:

> Accept:text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,_/_;q=0.8

Nothing fancy, I guess...

**Comment by leplatrem** [comment]
Then I guess you are receiving GeoJSON as the default content, because of bug https://github.com/mozilla-services/cornice/issues/150 :)

**Comment by Natim** [comment]
We fixed lots of this problem on the ACL branch already. I propose we merge this and default with no ACL and no AUTH so that we can continue to improve the software instead of redoing the all thing.

**Comment by almet** [comment]
+1
